import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "alacritty"

[font]
size = 16.0

[font.normal]
family = "TerminessNerdFontMono"

[window]
opacity = 0.9

[window.dimensions]
columns = 120
lines = 28
