-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Environment
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_SCALE_FACTOR", 1)
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)
hl.env("XCURSOR_SIZE", 24)
hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")
hl.env("HYPRCURSOR_SIZE", 24)
hl.env("OOMOX_QTSTYLEPLUGIN_THEME", "oomox")

-- Device setup
hl.monitor({
    output   = "HDMI-A-1",
    mode     = "2560x1440@144.00",
    position = "-2560x0",
    scale    = 1,
})

-- hl.monitor({
--     output   = "DP-3",
--     mode     = "1920x1080@60.0",
--     position = "16800x0",
--     scale    = 1,
-- })

hl.monitor({
    output   = "eDP-1",
    mode     = "2560x1600@165.00",
    position = "0x0",
    scale    = 1.33,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("uwsm app -- /usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("uwsm app -- waybar")
    hl.exec_cmd("uwsm app -- swaync")
    hl.exec_cmd("uwsm app -- swaybg -i $(cat ~/.cache/wal/wal)")
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("uwsm app -- nm-applet --indicator")
    hl.exec_cmd("uwsm app -- blueman-applet")
    hl.exec_cmd("uwsm app -- wl-paste --watch cliphist store")
    hl.exec_cmd("hyprctl setcursor rose-pine-hyprcursor 24")
end)


-- Load additional config
require("binds")
require("visuals")
