# These are not needed when using uwsm
# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = uwsm app -- /usr/lib/polkit-kde-authentication-agent-1
exec-once = uwsm app -- waybar
exec-once = uwsm app -- swaync
# exec-once = dunst
exec-once = uwsm app -- swaybg -i $(cat ~/.cache/wal/wal)
exec-once = hyprpm reload -n
exec-once = uwsm app -- nm-applet --indicator
exec-once = uwsm app -- blueman-applet
exec-once = uwsm app -- wl-paste --watch cliphist store 
# exec-once = dunst -conf .config/dunst/dunstrc
