# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#484b7b" }

# Hovered
hovered         = { fg = "#0b0908", bg = "#484b7b" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#b8bb26", italic = true }
find_position = { fg = "#a46e7e", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#b8bb26", bg = "#b8bb26" }
marker_copied   = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut      = { fg = "#fb4934", bg = "#fb4934" }

# Tab
tab_active   = { fg = "#0b0908", bg = "#c2c1c1" }
tab_inactive = { fg = "#c2c1c1", bg = "#5a658d" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#95908a" }

# Highlighting
# syntect_theme = "~/.config/yazi/Gruvbox-Dark.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#5a658d", bg = "#5a658d" }

# Mode
mode_normal = { fg = "#0b0908", bg = "#c2c1c1", bold = true }
mode_select = { fg = "#0b0908", bg = "#b8bb26", bold = true }
mode_unset  = { fg = "#0b0908", bg = "#d3869b", bold = true }

# Progress
progress_label  = { fg = "#915d72", bold = true }
progress_normal = { fg = "#c2c1c1", bg = "#5a658d" }
progress_error  = { fg = "#fb4934", bg = "#5a658d" }

# Permissions
permissions_t = { fg = "#c2c1c1" }
permissions_r = { fg = "#b8bb26" }
permissions_w = { fg = "#fb4934" }
permissions_x = { fg = "#b8bb26" }
permissions_s = { fg = "#665c54" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#766687" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#c2c1c1" }
active   = { fg = "#a46e7e" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#c2c1c1" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#5a658d" }
cand            = { fg = "#484b7b" }
rest            = { fg = "#766687" }
desc            = { fg = "#a46e7e" }
separator       = "  "
separator_style = { fg = "#c2c1c1" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#a46e7e" }
exec    = { fg = "#484b7b" }
desc    = { fg = "#766687" }
hovered = { bg = "#c2c1c1", bold = true }
footer  = { fg = "#5a658d", bg = "#c2c1c1" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#484b7b" },

    # Videos
    { mime = "video/*", fg = "#b8bb26" },
    { mime = "audio/*", fg = "#b8bb26" },

    # Archives
    { mime = "application/zip",             fg = "#a46e7e" },
    { mime = "application/gzip",            fg = "#a46e7e" },
    { mime = "application/x-tar",           fg = "#a46e7e" },
    { mime = "application/x-bzip",          fg = "#a46e7e" },
    { mime = "application/x-bzip2",         fg = "#a46e7e" },
    { mime = "application/x-7z-compressed", fg = "#a46e7e" },
    { mime = "application/x-rar",           fg = "#a46e7e" },

    # Fallback
    { name = "*", fg = "#c2c1c1" },
    { name = "*/", fg = "#484b7b" }
]

# : }}}
