# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#815b24" }

# Hovered
hovered         = { fg = "#1b150b", bg = "#815b24" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#b8bb26", italic = true }
find_position = { fg = "#17567b", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#b8bb26", bg = "#b8bb26" }
marker_copied   = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut      = { fg = "#fb4934", bg = "#fb4934" }

# Tab
tab_active   = { fg = "#1b150b", bg = "#c6c4c2" }
tab_inactive = { fg = "#c6c4c2", bg = "#697a7b" }

# Border
border_symbol = "│"
border_style  = { fg = "#99958f" }

# Highlighting
# syntect_theme = "~/.config/yazi/Gruvbox-Dark.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#697a7b", bg = "#697a7b" }

# Mode
mode_normal = { fg = "#1b150b", bg = "#c6c4c2", bold = true }
mode_select = { fg = "#1b150b", bg = "#b8bb26", bold = true }
mode_unset  = { fg = "#1b150b", bg = "#d3869b", bold = true }

# Progress
progress_label  = { fg = "#8d908e", bold = true }
progress_normal = { fg = "#c6c4c2", bg = "#697a7b" }
progress_error  = { fg = "#fb4934", bg = "#697a7b" }

# Permissions
permissions_t = { fg = "#c6c4c2" }
permissions_r = { fg = "#b8bb26" }
permissions_w = { fg = "#fb4934" }
permissions_x = { fg = "#b8bb26" }
permissions_s = { fg = "#665c54" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#456b7d" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#c6c4c2" }
active   = { fg = "#17567b" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#c6c4c2" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#697a7b" }
cand            = { fg = "#815b24" }
rest            = { fg = "#456b7d" }
desc            = { fg = "#17567b" }
separator       = "  "
separator_style = { fg = "#c6c4c2" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#17567b" }
exec    = { fg = "#815b24" }
desc    = { fg = "#456b7d" }
hovered = { bg = "#c6c4c2", bold = true }
footer  = { fg = "#697a7b", bg = "#c6c4c2" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#815b24" },

    # Videos
    { mime = "video/*", fg = "#b8bb26" },
    { mime = "audio/*", fg = "#b8bb26" },

    # Archives
    { mime = "application/zip",             fg = "#17567b" },
    { mime = "application/gzip",            fg = "#17567b" },
    { mime = "application/x-tar",           fg = "#17567b" },
    { mime = "application/x-bzip",          fg = "#17567b" },
    { mime = "application/x-bzip2",         fg = "#17567b" },
    { mime = "application/x-7z-compressed", fg = "#17567b" },
    { mime = "application/x-rar",           fg = "#17567b" },

    # Fallback
    { url = "*", fg = "#c6c4c2" },
    { url = "*/", fg = "#815b24" }
]

# : }}}
