[[plugin.prepend_fetchers]]
id    = "git" # Remove if Yazi > v26.1.22
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
id    = "git" # Remove if Yazi > v26.1.22
url   = "*/"
run   = "git"
group = "git"

[[plugin.prepend_previewers]]
mime = "application/{,g}zip"
run  = "lsar"

[[plugin.prepend_previewers]]
mime = "application/{tar,bzip*,7z*,xz,rar}"
run  = "lsar"

[[plugin.prepend_previewers]]
url = "*.md"
run  = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'
